:recycle: modularize application biophonie (#35)
* 🚧 add scaffolds for modularization

* 🚧 start to use convention plugin

* ✨ use AndroidApplicationConventionPlugin

* 🚧 extract firstlaunch feature

* 🚧 extract exploregeopoints feature

* 🚧 extract exploregeopoints feature

* ♻️ allow backup

* 🐛 add dagger compiler to init SyncSoundWorker

* 💡 add comment in manifest

* 🏗️ externalize databinding in plugin

* 🏗️ externalize BuildConfig in plugin

* 🏗️ split data package into geopoint and user

* 🔥 get rid of class NetworkUser

* 🏗️ extract AppPrefs from utils

* ♻️ extract templates to assets

* 🔥 clean :app build.gradle

* 👷 use typesafe project accessors

* 👷 update proguard rules

* 👷 create lint convention plugin

* 🐛 fix wrong package name for interceptor

* 👷 add detekt to build

* 🔥 remove :core:database

* 🚨 fix ktfmt and fix linter warnings

* 📝 add module graphs

* ⚡️ consider only kotlin file for ktfmt hook

* 🐛 avoid saving user twice

* 🐛 use template name instead of its display

* 🐛 make use of token in auth interceptor

* 📝 add documentation related to modularization

* 📝 update CHANGELOG

diff --git a/scripts/pre-commit/pre-commit.d/ktfmt b/scripts/pre-commit/pre-commit.d/ktfmt
--- a/scripts/pre-commit/pre-commit.d/ktfmt
+++ b/scripts/pre-commit/pre-commit.d/ktfmt
@@ -1,18 +1,27 @@
 #!/usr/bin/env bash
 
 echo "Running ktfmt check on staged files..."
-CHANGED_FILES="$(git diff --staged --name-only | tr '\n' ':' )"
+MODULES="$(./gradlew -q modules)"
 OUTPUT="/tmp/ktfmt-$(date +%s)"
-./gradlew --quiet ktfmtPreCommit --include-only="$CHANGED_FILES" > "$OUTPUT"
-EXIT_CODE=$?
-if [ $EXIT_CODE -ne 0 ]; then
-  cat "$OUTPUT"
+for module in $MODULES; do
+  path="${module//://}/"
+  changed_files="$(git diff --staged --name-only "$path" |grep -e "\.kts" -e "\.kt")"
+  if [[ -z $changed_files ]]; then
+    continue
+  fi
+  echo "ktfmt: Inspecting module $module"
+  relative_files="$(echo "$changed_files" | sed "s#^$path##g" | tr '\n' ':')"
+  ./gradlew --quiet "$module":ktfmtPreCommit --include-only="$relative_files" >> "$OUTPUT"
+  EXIT_CODE=$?
+  if [ $EXIT_CODE -ne 0 ]; then
+    cat "$OUTPUT"
+    rm "$OUTPUT"
+    echo "*******************************************************"
+    echo " ktfmt failed in module $module"
+    echo " Please fix the above issues before committing"
+    echo " Tip: run the formatter with './gradlew ktfmtFormat'"
+    echo "*******************************************************"
+    exit $EXIT_CODE
+  fi
   rm "$OUTPUT"
-  echo "*******************************************************"
-  echo "|                    ktfmt failed                     |"
-  echo "| Please fix the above issues before committing       |"
-  echo "| Tip: run the formatter with './gradlew ktfmtFormat' |"
-  echo "*******************************************************"
-  exit $EXIT_CODE
-fi
-rm "$OUTPUT"
+done
