:stethoscope: add pre-push and pre-commit hooks (#50)
* ⬆️ upgrade AGP and kotlin versions

* 👷 replace kapt by ksp when applicable

* 👷 Add dependency analysis

* 🚨 take into account buildHealth advice

* ♻️ refactor :core:model to be jvm only

* 🐛 specify testrunner in individual build.gradle

* 🔧 sort dependencies build files

* 🏗️ refactor composelibrary into compose plugin

* 🩺 parallelize health checks

* 🚧 add sort-dependencies check

diff --git a/scripts/pre-commit/pre-commit b/scripts/pre-commit/pre-commit
--- a/scripts/pre-commit/pre-commit
+++ b/scripts/pre-commit/pre-commit
@@ -1,13 +1,24 @@
 #!/usr/bin/env bash
 
 echo "Running git pre-commit hooks..."
-for hook in "$(dirname "$0")/pre-commit.d"/*; do
-    "$hook"
-    RESULT=$?
-    if [ $RESULT != 0 ]; then
-        echo "pre-commit.d/$hook returned non-zero: $RESULT, abort commit"
-        exit $RESULT
-    fi
+pids=()
+isSuccess=true
+for hook in "$(dirname "$0")/pre-commit.d"/*.sh; do
+    "$hook" &
+    pids+=($!)
 done
 
-exit
+for pid in ${pids[*]}; do
+  wait "$pid"
+  RESULT=$?
+  if [ $RESULT != 0 ]; then
+    isSuccess=false
+    echo "pre-commit.d/$hook returned non-zero: $RESULT, commit will abort"
+  fi
+done
+
+if [ $isSuccess = true ]; then
+  exit 0
+else
+  exit 1
+fi
